# Generated by Django 2.1.1 on 2018-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('city_id', models.CharField(max_length=10)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hotel', models.CharField(max_length=255)),
            ],
        ),
    ]
